storage = 'DB'
adminURL = 'http://localhost:8080/admin/orgFiles?orgName='

[origins]
allowedOrigins = ["http://localhost:3000"]

[devportal.store]
host = "pg-82d26742-afe1-4ed2-bf5e-0034635f0a07-ecidevpo688499110-chore.k.aivencloud.com"
port = 23658
user = "avnadmin"
password = ""
database = "defaultdb"

[devportal.models]
awsAccessKeyId = ""
awsSecretAccessKey = ""
awsRegion = ""

